/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * java mavlink generator tool. It should not be modified by hand.
 */

// MESSAGE ACTUATOR_CONTROL_TARGET PACKING
package com.MAVLink.test.tests;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

import com.MAVLink.MAVLinkPacket;
import com.MAVLink.Messages.MAVLinkMessage;
import com.MAVLink.Messages.MAVLinkPayload;

/**
* Set the vehicle attitude and body angular rates.
*/
public class test_msg_actuator_control_target{
    long time_usec = 123456789;
    float controls[] = new float[]{1,2,3,4,5,6,7,8};
    public short group_mlx = 25000;

    @Test
    public void test(){
        msg_actuator_control_target packet = new msg_actuator_control_target();
        packet.time_usec = time_usec;
        packet.controls = controls;
        packet.group_mlx = group_mlx;
        MAVLinkPacket mAVLinkPacket = packet.pack();

        packet = null;
        packet = msg_actuator_control_target(mAVLinkPacket);

        assertEquals("msg_actuator_control_target.time_usec was not parsed correctly.", time_usec, packet.time_usec);
        assertEquals("msg_actuator_control_target.controls was not parsed correctly.", controls, packet.controls);
        assertEquals("msg_actuator_control_target.group_mlx was not parsed correctly.", group_mlx, packet.group_mlx);
    }
}
